# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
ar=np.arange(0,23)
value=np.random.randint(10,23,1)
print("Numpy array: ",ar)
print("value of array elemenets: ",value)

Numpy array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
value of array elemenets:  [17]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [16]:
# Solution
ar1=np.arange(1,50,2)
print("Array is: ",ar1)
print("Length of array: ",len(ar1))

Array is:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Length of array:  25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [18]:
# Solution
ar2=np.linspace(4,7,27)
print("Array is: ",ar2)

Array is:  [4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [25]:
# Solution
matrix= np.random.random((5,4))
print("Original Matrix is: ",matrix)
print("round off matrix is: ",np.round(matrix,2))

Original Matrix is:  [[0.29267134 0.56519517 0.88230283 0.43288181]
 [0.90379872 0.82313063 0.16515691 0.3709341 ]
 [0.36659939 0.48498748 0.5504091  0.26735129]
 [0.8354363  0.62957249 0.67463285 0.96523848]
 [0.48628407 0.58132148 0.80792635 0.24305893]]
round off matrix is:  [[0.29 0.57 0.88 0.43]
 [0.9  0.82 0.17 0.37]
 [0.37 0.48 0.55 0.27]
 [0.84 0.63 0.67 0.97]
 [0.49 0.58 0.81 0.24]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [27]:
# Solution
matrix1=np.random.randint(5,15,(5,5))
print("Matrix of random integer is: ",matrix1)

Matrix of random integer is:  [[12 13  8  5 14]
 [11  6  8 13  9]
 [ 5 11 11  6  9]
 [ 7 13 12  8 13]
 [13  5 12 11 10]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [36]:
# Solution
ar3=np.zeros(20)
ar4=ar3.astype(np.int32)
print("one dimensional array of random length is: ",ar3)
print("one dimensional array of random length of data type int32 is: ",ar4)
print("Data type is: ",ar4.dtype)

one dimensional array of random length is:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
one dimensional array of random length of data type int32 is:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Data type is:  int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [34]:
# Solution
matrix3=1*np.ones((3,3))
matrix3=matrix3.astype(np.float32)
print("Matrix of two dimensional array of ones: ",matrix3)
print("Data type is: ",matrix3.dtype)

Matrix of two dimensional array of ones:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Data type is:  float32


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [48]:
# Solution
matrix4=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print("Shape of the matrix is: ",matrix4.shape)
print("Type of the matrix is: ",type(matrix4))
print("dtype of the matrix is: ",matrix4.dtype)

Shape of the matrix is:  (5, 5)
Type of the matrix is:  <class 'numpy.ndarray'>
dtype of the matrix is:  int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [63]:
# Solution
matrix4=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(matrix4)
matrix5=matrix4.flatten()
mid_value=matrix5[int(len(matrix5)/2)]
print("The center element is: ",mid_value)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
The center element is:  3
Type of Mid Value is:  <class 'numpy.ndarray'>


#### 10. Print the all the elements of 3rd row of the matrix

In [71]:
# Solution
matrix6=matrix4[2]
print("Third row of the matrix is: ",matrix6)

Third row of the matrix is:  [ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [74]:
# Solution
matrix7=matrix4[:,3:4]
print("4th column of the matrix is: ",matrix7)

4th column of the matrix is:  [[34]
 [65]
 [76]
 [54]
 [ 5]]


#### 12. Print the 4 corner pixels of the matrix

In [103]:
# Solution
matrix8=matrix4[[0,0,4,4],[0,4,0,4]]
print("Four corner of the matrix is: ",matrix8)

Four corner of the matrix is:  [ 9 45 23  8]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [121]:
# Solution 
m1=np.array([[50,34],[34,65]])
m3=np.array([[3,76,3],[6,54,6],[8,5,8]])
m2=np.array([[7,8],[23,12]])
print("M1 is: ",m1)
print("M2 is: ",m2)
print("M3 is: ",m3)

M1 is:  [[50 34]
 [34 65]]
M2 is:  [[ 7  8]
 [23 12]]
M3 is:  [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [123]:
# Solution
m4=m1.reshape((1,4))
m5=m2.reshape((1,4))
m6=m3.reshape((1,9))
print("one dimensional vector of m1 is: ",m4)
print("one dimensional vector of m2 is: ",m5)
print("one dimensional vector of m3 is: ",m6)

one dimensional vector of m1 is:  [[50 34 34 65]]
one dimensional vector of m2 is:  [[ 7  8 23 12]]
one dimensional vector of m3 is:  [[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [126]:
# Solution
m7=np.concatenate((m1,m2),axis=1)
m8=np.concatenate((m1,m2),axis=0)
print("vertical concatenation is: ",m7)
print("horizontal concatenation is: ",m8)

vertical concatenation is:  [[50 34  7  8]
 [34 65 23 12]]
horizontal concatenation is:  [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [127]:
# Solution
m9=m1+m2
m10=m1-m2
m11=m1*m2
m12=m1/m2
print("M1+M2= ",m9)
print("M1-M2= ",m10)
print("M1*M2= ",m11)
print("M1/M2= ",m12)

M1+M2=  [[57 42]
 [57 77]]
M1-M2=  [[43 26]
 [11 53]]
M1*M2=  [[350 272]
 [782 780]]
M1/M2=  [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [134]:
# Solution
m13=m3[1:,0:2]
m14=m1+m13
print("M1+M3= ",m14)

M1+M3=  [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [167]:
# Solution
m15=m1[0:2,0:1]
m16=m1[0:2,1:2]
me1=m15.mean()
me2=m16.mean()
me=np.matrix([me1,me2])
m17=np.concatenate((m1,me),axis=0)
print("M4 = ",m17)

M4 =  [[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [166]:
# Solution
m18=m3*m17
print("M1*M3 = ",m18)

M1*M3 =  [[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [175]:
# Solution
matrix9=matrix4.mean(axis=1)
matrix10=matrix4.var(axis=1)
matrix11=matrix4.std(axis=1)
print("Maximum of mean: ",max(matrix9))
print("Minimum of mean: ",min(matrix9))
print("Maximum of standard deviation: ",max(matrix11))
print("Minimum of standard deviation: ",min(matrix11))
print("Maximum of variance: ",max(matrix10))
print("Minimum of variance: ",min(matrix10))

Maximum of mean:  32.6
Minimum of mean:  11.2
Maximum of standard deviation:  28.63843571147
Minimum of standard deviation:  6.305553108173779
Maximum of variance:  820.1600000000001
Minimum of variance:  39.760000000000005


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [29]:
# Solution 
run_scored=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
balls_faced=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
msd_avg=np.average(run_scored[0:1,0:4])
kholi_avg=np.average(run_scored[1:2,0:4])
Rohit_avg=np.average(run_scored[2:3,0:4])
Rahul_avg=np.average(run_scored[3:4,0:4])
Dhawan_avg=np.average(run_scored[4:5,0:4])
Average_team=np.array([msd_avg,kholi_avg,Rohit_avg,Rahul_avg,Dhawan_avg])
Average_team=np.sort(Avg_team)
print("Average of the team is: ",Average_team)
print("Average of the team in descending way is: ",Average_team[::-1])
strike_rate=run_scored/balls_faced*100
msd_stk=np.sum(strike_rate[0:1,0:4])/4
kholi_stk=np.sum(strike_rate[2:3,0:4])/4
Rohit_stk=np.sum(strike_rate[2:3,0:4])/4
Rahul_stk=np.sum(strike_rate[3:4,0:4])/4
Dhawan_stk=np.sum(strike_rate[4:5,0:4])/4
stk_team=np.array([msd_stk,kholi_stk,Rohit_stk,Rahul_stk,Dhawan_stk])
stk_team=np.sort(stk_team)
print("Strike rate of the team is: ",stk_team)
print("Strike Rate of the team in descending way is: ",stk_team[::-1])

Average of the team is:  [13.25 29.   47.25 51.5  53.5 ]
Average of the team in descending way is:  [53.5  51.5  47.25 29.   13.25]
Strike rate of the team is:  [ 47.96296296  62.17703913  62.17703913  94.91125541 162.99554687]
Strike Rate of the team in descending way is:  [162.99554687  94.91125541  62.17703913  62.17703913  47.96296296]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [46]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
passed=(marks[::-1]>50).sum()
failed=(marks[::-1]<50).sum()
print("Number of students Passed: ",passed)
print("Number of students Failed: ",failed)

Number of students Passed:  7
Number of students Failed:  3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [61]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
ind1=np.where((marks<=49)|(marks>=45)|(marks>=80))
marks[ind1]=marks[ind1]+5
ind2=np.where(marks[ind1]>=100)
marks[ind2]=100
print("All the students marks is: ",marks[ind1])

All the students marks is:  [ 70  89  52  61  94 100  53  82  85  44]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [65]:
# Solution
import time
def lst():
    x=list(range(1,60000))
    y=list(range(1,60000))
    res=[]
    for i in range (len(x)):
        res.append((((x[i]**2)+8)/y[i]))
        
def npy():
    x=np.array(range(1,60000))
    y=np.array(range(1,60000))
    res=((x**2)+8)/y
    
start=time.time()
%time lst()
end = time.time()
print("The time taken for list is : ",end-start)
start1=time.time()
%time npy()
end1=time.time()
print("The time taken for numpy is : ",end1-start1)

Wall time: 34.1 ms
The time taken for list is :  0.03604841232299805
Wall time: 8.05 ms
The time taken for numpy is :  0.00804758071899414


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [64]:
# Solution
import urllib.request
url = urllib.request.urlopen('https://github.com/Palaniappa619/Numpy_Basics')
url